server:
  port: 9527
spring:
  application:
    name: cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gatway-9527.com
    prefer-ip-address: true

info:
  app.name: muchi.zuul
  company.name: www.muchi

#提供 代理 加路由 加过滤三大功能
zuul:
  prefix: /mz
  ignored-services: "*"
  routes:
    mz.serviceOd: cloud-dept
    mz.path: /mzdept/**

