server:
  port: 3344

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YBriel/cloud-config.git
          username:
          password: